# Generated by Django 3.0.3 on 2020-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('contact_no', models.IntegerField()),
            ],
        ),
    ]
