# Generated by Django 3.0.3 on 2020-02-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doner',
            name='age',
            field=models.IntegerField(default=18),
        ),
    ]
